import { Hero } from './hero';

export const HEROES: Hero[] = [
  { id: 1, name: 'Real Madrid FC', descripcion:"El Real Madrid Club de Fútbol es un club polideportivo de la ciudad de Madrid, España. Fundado el 6 de marzo de 1902 como Sociedad Madrid Foot-Ball Club, en su rama futbolística - que juega en la Primera División de España - fue denominado por la FIFA el Mejor Club del Siglo XX." },
  { id: 2, name: 'Manchester City', descripcion:"El Manchester City es conocido por su estilo de juego vistoso y ofensivo, bajo la dirección de varios entrenadores destacados, como Pep Guardiola, quien ha dejado una marca distintiva en el equipo desde su llegada en 2016. Guardiola ha llevado al City a numerosos títulos domésticos e internacionales, implementando un enfoque de posesión de balón y presión alta." },
  { id: 3, name: 'Bayern Munich', descripcion:"El Bayern Munich es uno de los clubes de fútbol más exitosos y reconocidos del mundo. Con sede en Múnich, Alemania, el Bayern ha dominado la escena futbolística tanto a nivel nacional como internacional. Con un estilo de juego agresivo y una cantera prolífica, el club ha ganado numerosos títulos de la Bundesliga, así como múltiples títulos de la Liga de Campeones de la UEFA. Es conocido por su enfoque en el desarrollo de talento local y por atraer a algunos de los mejores jugadores del mundo."  },
  { id: 4, name: 'Paris S. German', descripcion:"Fundado en 1970, el Paris Saint-Germain es uno de los clubes de fútbol más prominentes de Francia. Con sede en París, el club ha emergido como una potencia tanto en la liga doméstica como en competiciones europeas. Con inversiones significativas de capital extranjero, el PSG ha construido un equipo estelar, con jugadores como Neymar, Kylian Mbappé y Lionel Messi. Han ganado múltiples títulos de la Ligue 1 y han sido contendientes en la Liga de Campeones de la UEFA." },
  { id: 5, name: 'FC Liverpool', descripcion:"El Liverpool Football Club, fundado en 1892, es uno de los clubes más exitosos y populares de Inglaterra. Basado en la ciudad de Liverpool, el equipo tiene una rica historia y una base de seguidores apasionados en todo el mundo. Conocido por su estilo de juego rápido y emocionante, el Liverpool ha ganado múltiples títulos de la Premier League, así como numerosas FA Cups y Ligas de Campeones de la UEFA. Bajo la dirección de Jürgen Klopp, el equipo ha revivido su gloria, destacando por su intensidad y juego colectivo." },
  { id: 6, name: 'Inter de Milan', descripcion:"El Inter de Milán es uno de los clubes de fútbol más grandes y exitosos de Italia. Fundado en 1908, el club tiene su sede en Milán y cuenta con una rica historia de éxitos nacionales e internacionales. Conocido por su enfoque táctico y defensivo, el Inter ha ganado múltiples títulos de la Serie A y ha tenido éxito en competiciones europeas, incluida la Liga de Campeones de la UEFA. El equipo ha sido el hogar de legendarios jugadores y entrenadores a lo largo de los años, y sigue siendo un contendiente en el fútbol italiano e internacional." },
  { id: 7, name: 'AS Roma', descripcion:"La AS Roma es uno de los clubes de fútbol más emblemáticos de Italia. Fundado en 1927, el club tiene su sede en Roma y cuenta con una base de seguidores apasionados en toda Italia y más allá. Con un estilo de juego ofensivo y una rica historia, la Roma ha tenido éxito en la Serie A y ha competido en competiciones europeas como la Liga de Campeones de la UEFA. El equipo es conocido por su identidad y conexión con la ciudad de Roma, lo que lo convierte en un símbolo de orgullo para los romanos." },
  { id: 8, name: 'Chelsea FC', descripcion:"El Chelsea Football Club es uno de los clubes de fútbol más destacados de Inglaterra. Fundado en 1905, el club tiene su sede en Londres y ha experimentado un éxito significativo en la Premier League y en competiciones europeas. Con una rica historia y una base de seguidores leales, el Chelsea ha ganado múltiples títulos de liga, FA Cups y la Liga de Campeones de la UEFA. Con inversiones financieras significativas en los últimos años, el club ha sido capaz de atraer a algunos de los mejores talentos del mundo y competir a nivel nacional e internacional." },
  { id: 10, name: 'Manchester United', descripcion:"El Manchester United es uno de los clubes de fútbol más grandes y exitosos del mundo. Basado en Manchester, Inglaterra, el club tiene una rica historia que se remonta a su fundación en 1878. Conocido como los Diablos Rojos, el United ha ganado numerosos títulos de la Premier League, FA Cups y ha tenido éxito en competiciones europeas, incluida la Liga de Campeones de la UEFA. El club ha sido el hogar de algunos de los jugadores más legendarios del fútbol y ha tenido una influencia global masiva, con una base de seguidores leales en todo el mundo." }
];